### PR TITLE
pl

### PR DESCRIPTION
**Pull request by tomlimi**
Morphology analysis for Polish with spaCy and Morfeusz2.

### CODE REVIEW

**Comment by gabrielStanovsky** [comment]
@Tom556 Looks great! thanks!
can you add to the readme the external dependencies which are needed for Polish? (e.g., Morfeusz)

**Comment by gabrielStanovsky** [comment]
I mean, just writing down the name of the packages, so people can install them separately.

**Comment by tomlimi** [comment]
Just added additional installation steps for Polish to README.

**Comment by gabrielStanovsky** [comment]
Thanks! merging now.

**Pull request merged**
